[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/wp-content/*"
  to = "https://blogs.vocallabs.ai/wp-content/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/wp-includes/*"
  to = "https://blogs.vocallabs.ai/wp-includes/:splat"
  status = 200
  force = true
